### ISSUE TITLE
Really Nice Work!

### ISSUE THREAD

**Issue by PkuRainBow** [mseg-dataset/mseg-api#1]
Really nice work and I hope you could release the remained 3 repos so that the community could conduct research along this direction. 

> This repo is the first of 4 repos that introduce our work. It provides utilities to download the MSeg dataset (which is nontrivial), and prepare the data on disk in a unified taxonomy.
> 
> In a few weeks, we will add the TaxonomyConverter class to this repo that supports on-the-fly mapping to a unified taxonomy during training.

**Comment by johnwlambert** [comment]
Thanks @PkuRainBow. We've released the semantic segmentation repo here: https://github.com/mseg-dataset/mseg-semantic. The other repos will be added later this month.
