### ISSUE TITLE
Problem with COCOPanoptic dataset

### ISSUE THREAD

**Issue by jdavidd** [mseg-dataset/mseg-api#22]
Hello I have some problem with remap and relabelling of COCOPanoptic dataset. Firstly I needed to download it separately due to some script problem.

First here is error from remap log, but the script completed 100% train and validation 0%.
![image](https://user-images.githubusercontent.com/26500800/110549902-6e637f00-813b-11eb-8c6b-f55e1648dfa4.png)

Second error in relabeling log. it also says it has completed 100% train and validation 0%.
![image](https://user-images.githubusercontent.com/26500800/110552271-aec4fc00-813f-11eb-9c5d-31aa731b14bd.png)
![image](https://user-images.githubusercontent.com/26500800/110552334-d1571500-813f-11eb-86ca-52fd96cb55fd.png)

After this I tried to run the unit test, and it crashes at cocopanoptic dataset.
![image](https://user-images.githubusercontent.com/26500800/110547432-94d3eb00-8138-11eb-9472-59527d9f717f.png)

**Comment by johnwlambert** [comment]
Hi @jdavidd, thanks for your interest in our work. It looks like during remapping, some of your images are corrupted, so `imageio` cannot read them. Can you try something like
```python
import glob
import imageio
COCO_IMG_DIR = /path/to/your/dir
for fpath in glob.glob(f'{COCO_IMG_DIR}/*.jpg'):
      try:
            img = imageio.imread(fpath)
      else:
           print(f'Failure on {fpath}')
```
to find the corrupted images? Can you explain here the differences between your download process for COCOPanoptic, vs. our download script? If there was an error you saw when downloading it with our script, please share it also

**Comment by jdavidd** [comment]
So i ran your code, and all images were ok.
I downloaded again no_reg datasets and there was no error. After that the remap was ok. But the error on relabeling cocoPanoptic doesn't disappear (assert label_img.ndim == 2).

**Comment by johnwlambert** [comment]
Cool, do you mind adding a try/except statement before the line that crashes and printing out the path to the label image that can't be loaded properly? Then we can debug from there.

**Comment by jdavidd** [comment]
I dont know exactly where is the part, where the label is read. Here s the line were the code crash.
![image](https://user-images.githubusercontent.com/26500800/110703184-1e002600-81fc-11eb-9a40-112eb59ae12c.png)

**Comment by jdavidd** [comment]
Hello, @johnwlambert  i made a script, to read labels (train) and verify their dimension. After executing the script resulted in 11090 labels, with label.ndim=3. Here are some example. 
![image](https://user-images.githubusercontent.com/26500800/111692717-69d45000-8838-11eb-97cd-da85f8137d71.png)

I dont know exactly what to do now, i run every script in order, the problem seems to be only on COCOPanoptic dataset.

**Comment by johnwlambert** [comment]
Hi @jdavidd, just to confirm, you already downloaded COCO Panoptic, right? (using this script https://github.com/mseg-dataset/mseg-api/blob/master/download_scripts/mseg_download_cocopanoptic.sh)
And you found all of the following files, and the directories exist?

Also to confirm, you are having trouble when you run https://github.com/mseg-dataset/mseg-api/blob/master/download_scripts/mseg_remap_cocopanoptic.sh?

```python

python -u $REPO_ROOT/mseg/label_preparation/dump_coco_semantic_labels.py \
	--num_processes $NUM_CORES_TO_USE

# ----------- Remapping -----------------------------------

now=$(date +"%Y %m %d @ %H:%M:%S")
echo "Started remapping at "$now

ORIG_DNAME="coco-panoptic-201"
REMAP_DNAME="coco-panoptic-133"

ORIG_DROOT=$COCOP_DST_DIR

python -u $REPO_ROOT/mseg/label_preparation/remap_dataset.py \
	--orig_dname $ORIG_DNAME --remapped_dname $REMAP_DNAME \
	--orig_dataroot $ORIG_DROOT --remapped_dataroot $ORIG_DROOT \
	--num_processes $NUM_CORES_TO_USE


now=$(date +"%Y %m %d @ %H:%M:%S")
echo "Completed remapping at "$now
```

So after running `dump_coco_semantic_labels.py`, you encounter an error I haven't seen before.

https://github.com/mseg-dataset/mseg-api/blob/master/mseg/label_preparation/dump_coco_semantic_labels.py

All of the semantic labels that are dumped are 2-dimensional label maps. I hate to say this but you will have to step through this in one process on your machine to see what the issue is. (I've run this multiple times with no issues)

**Comment by ionicaML** [comment]
Hello,
When I try to re-download the mseg dataset, I too get the same errors as @jdavidd mentioned earlier with COCOPanoptic  (even when doing it manually). Would you mind sharing your environment, python version and OS version you are running @johnwlambert ? I am currently using Python 3.8, Ubuntu 18.04 and the requirements mentioned in the repo. I tried running this on an AWS EC2 machine too, and I got the same errors.

I will be back with updates after I try to apply some fixes.

**Comment by jdavidd** [comment]
Hi @johnwlambert , you were right there were some problems with cocopanoptic labels. This happened because, the line that should dump labels from json to png was commented. Thank you for your response.
