### ISSUE TITLE
Test dataset annotation

### ISSUE THREAD

**Issue by lxtGH** [mseg-dataset/mseg-api#28]
Hi! @johnwlambert  
Since the train datasets have been relabeled.
![image](https://user-images.githubusercontent.com/17202268/117142562-6d209c80-ade2-11eb-90d3-4509adac421f.png)

Why the test sets are not relabed? How to test the these test test?

**Comment by lxtGH** [comment]
Did you just transfer these gt mask into unified taxonomy of
194 classes using NaiveTaxonomyConverter?

**Comment by johnwlambert** [comment]
Hi @lxtGH, please refer to section 3.2 of our [paper](http://vladlen.info/papers/MSeg.pdf):
"We re-annotate only the datasets used for learning, leaving the evaluation datasets intact."

We did this for fair comparison with other results on these established benchmarks. Indeed, we were the runner-up at the 2020 Robust Vision Challenge that used several of these benchmarks.

Regarding how to project results in the universal taxonomy into a test dataset's taxonomy, please refer to the section entitled "Using the MSeg taxonomy on a held-out dataset." of our [paper](http://vladlen.info/papers/MSeg.pdf) on page 6. We discuss this in detail.
