### ISSUE TITLE
code, data and trained models

### ISSUE THREAD

**Issue by achreff** [mseg-dataset/mseg-api#3]
hello
Cloud you please upload the code, data and
trained models.

Best regards

**Comment by johnwlambert** [comment]
Hi @achreff, code and models will be available this month. Data is already available: public downloads [here](https://github.com/mseg-dataset/mseg-api/tree/master/download_scripts) and relabeled data [here](https://github.com/mseg-dataset/mseg-api/tree/master/mseg/relabeled_data).

**Comment by achreff** [comment]
Thank you so much
I hope find your code with pretrained model on Mseg, Coco-stuff, Ade20k....
Best regard

**Comment by johnwlambert** [comment]
Hi @achreff, I believe you have found our inference code and pretrained models at https://github.com/mseg-dataset/mseg-semantic, so I'm closing this issue for now. Please let me know if you have further questions about models/inference code in that repo.
