### ISSUE TITLE
Can't find supplement mentioned in paper

### ISSUE THREAD

**Issue by XAVILLA** [mseg-dataset/mseg-api#35]
Hi, I'm having a hard time finding the supplement material described in the paper. In a previous issue you mentioned that it will get updated to arxiv but I can't find it there. Can you let me know where should I search for this document?

Thanks!

**Comment by linzhiqiu** [comment]
Any update on this issue?

**Comment by johnwlambert** [comment]
Hi @XAVILLA @linzhiqiu @krumo, we've added the Supplement in our journal-length paper on Arxiv as the "Appendix".

https://arxiv.org/abs/2112.13762

Please see pages 15-23. Some of the Supplement is now included in the main text of the journal version. Please let me know if you have further questions.
