### ISSUE TITLE
Final taxonomy

### ISSUE THREAD

**Issue by orsic** [mseg-dataset/mseg-api#4]
Hello,

thank you for interesting work.

I have a question regarding the final `class name -> id mapping`.
How can one obtain such mapping using the mseg-api?
Are the label IDs sorted alphabetiaclly according to [the `universal` column](https://github.com/mseg-dataset/mseg-api/blob/master/mseg/class_remapping_files/MSeg_master.tsv)?

**Comment by johnwlambert** [comment]
Hi @orsic , thanks very much for your interest in our work. For training and test dataset taxonomies, class indices come from the order in which they appear in the mseg/dataset_lists/*/*_names.txt file (see [here](https://github.com/mseg-dataset/mseg-api/blob/master/mseg/utils/names_utils.py#L59) ).

For the universal taxonomy, we use the row index in the master tsv (just added this [function](https://github.com/mseg-dataset/mseg-api/blob/master/mseg/utils/names_utils.py#L35) ). Let me know if I can clear anything else up.
